import bocha from './browser-internal.js';

export const testCase = bocha.testCase;
export const assert = bocha.assert;
export const refute = bocha.refute;
export const sinon = bocha.sinon;
export const stub = bocha.stub;
export const spy = bocha.spy;
export const fakeClock = bocha.fakeClock;
export const waitStub = bocha.waitStub;
export const timeout = bocha.timeout;
export const dom = bocha.dom;
export const defaults = bocha.defaults;
export const defaultsDeep = bocha.defaultsDeep;
export const localToUtc = bocha.localToUtc;
export const utcToLocal = bocha.utcToLocal;
export const catchError = bocha.catchError;
export const catchErrorAsync = bocha.catchErrorAsync;
export const click = bocha.dom.clickAndTick;
export const setValue = bocha.dom.setValueAndTick;
export const focus = bocha.dom.focusAndTick;
export const blur = bocha.dom.blurAndTick;
export const keydown = bocha.dom.keydownAndTick;
export const keydownWithModifiers = bocha.dom.keydownAndTickWithModifiers;
export const mouseup = bocha.dom.mouseupAndTick;
export const pasteIntoInput = bocha.dom.pasteIntoInputAndTick;
export const htmlToElement = bocha.dom.htmlToElement;
export const detachElements = bocha.dom.detachElements;
export const $ = (selector => document.querySelector(selector));
export const $$ = (selector => document.querySelectorAll(selector));